# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update TUI versions
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Every Monday at 1PM UTC (9AM EST)
    # first - minutes
    # second - hours
    # the last * - is day of the week (0 - 6 or SUN-SAT) text
    - cron:  '25,30 * * * *'

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Update dependencies
        run: |
          npx -p npm-check-updates ncu -u
          npm install
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            branch: update-dependencies
            commit-message: "feat: update report and use cron"
            committer: GitHub <inna-i@github.com>
            title: Update dependencies
            body: |
              Update report
              - Updated with *today's* date
              - Auto-generated by [create-pull-request][1]

              [1]: https://github.com/peter-evans/create-pull-request
            assignees: inna-i
            reviewers: inna-i

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
